"""Generate/check source-derived constants. No devices, MMIO or network.

--archive PATH imports numeric facts from the pinned AMD source archive.
--write writes only the generated catalog JSON/header; never edits consumers.
Without --write, compare generated bytes with committed artifacts (fail closed).
"""
import argparse
import hashlib
import json
import re
import tarfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
DATA = HERE / 'catalog.json'
HEADER = ROOT / 'inc/gc-source-map-20260930/bc250_gc_source_map.h'
ARCHIVE_SHA = 'f848df42bd4ac31a4918188c6723660d3c6dd7591b63a6419123dcbc23ecf328'
PREFIX = 'cachyos-7.2.8-1/drivers/gpu/drm/amd/'
FILES = ('include/cyan_skillfish_ip_offset.h',
         'include/asic_reg/gc/gc_10_1_0_offset.h',
         'include/asic_reg/gc/gc_10_1_0_sh_mask.h')
# Names are AMD names, not guesses based on legacy byte offsets.
NAMES = ('GRBM_STATUS', 'GRBM_GFX_INDEX', 'GRBM_GFX_CNTL',
         'CP_ME_CNTL', 'CP_RB0_BASE', 'CP_RB0_BASE_HI', 'CP_RB0_CNTL',
         'CP_RB0_RPTR', 'CP_RB0_WPTR', 'CP_RB0_WPTR_HI',
         'SPI_PG_ENABLE_STATIC_WGP_MASK', 'CC_GC_SHADER_ARRAY_CONFIG',
         'RLC_PG_ALWAYS_ON_WGP_MASK', 'CP_MEC_CNTL', 'CP_HQD_ACTIVE',
         'CP_HQD_VMID', 'CP_HQD_PQ_BASE', 'CP_HQD_PQ_BASE_HI',
         'GCVM_L2_CNTL', 'GCVM_CONTEXT0_CNTL', 'SDMA0_GFX_RB_BASE') + tuple(
             'SCRATCH_REG' + str(i) for i in range(8))
FIELDS = ('GRBM_GFX_INDEX__INSTANCE_INDEX__SHIFT',
          'GRBM_GFX_INDEX__INSTANCE_INDEX_MASK',
          'GRBM_GFX_INDEX__SA_INDEX_MASK', 'GRBM_GFX_INDEX__SE_INDEX_MASK',
          'GRBM_GFX_INDEX__SA_INDEX__SHIFT',
          'GRBM_GFX_INDEX__SE_INDEX__SHIFT',
          'GRBM_GFX_INDEX__SA_BROADCAST_WRITES_MASK',
          'GRBM_GFX_INDEX__INSTANCE_BROADCAST_WRITES_MASK',
          'GRBM_GFX_INDEX__SE_BROADCAST_WRITES_MASK',
          'GRBM_GFX_CNTL__PIPEID__SHIFT', 'GRBM_GFX_CNTL__MEID__SHIFT',
          'GRBM_GFX_CNTL__VMID__SHIFT', 'GRBM_GFX_CNTL__QUEUEID__SHIFT',
          'GRBM_GFX_CNTL__PIPEID_MASK', 'GRBM_GFX_CNTL__MEID_MASK',
          'GRBM_GFX_CNTL__VMID_MASK', 'GRBM_GFX_CNTL__QUEUEID_MASK')


def definitions(text):
    rows = {}
    for n, line in enumerate(text.splitlines(), 1):
        m = re.fullmatch(r'\s*#define\s+(\w+)\s+(0x[0-9a-fA-F]+|[0-9]+)[uUlL]*\s*', line)
        if m:
            key, value = m.groups()
            if key in rows and rows[key][0] != int(value, 0):
                raise ValueError('Conflicting numeric definition: ' + key)
            rows.setdefault(key, (int(value, 0), n))
    return rows


def import_archive(path):
    with path.open('rb') as stream:
        if hashlib.file_digest(stream, 'sha256').hexdigest() != ARCHIVE_SHA:
            raise ValueError('Unexpected archive SHA-256')
    texts, hashes = {}, {}
    with tarfile.open(path, 'r|gz') as archive:
        for member in archive:
            name = member.name.removeprefix(PREFIX)
            if member.name.startswith(PREFIX) and name in FILES:
                if not member.isfile() or name in texts:
                    raise ValueError('Invalid/duplicate source member')
                data = archive.extractfile(member).read()
                texts[name] = data.decode('utf-8')
                hashes[name] = hashlib.sha256(data).hexdigest()
    if set(texts) != set(FILES):
        raise ValueError('Missing primary source')
    ip, offsets, fields = (definitions(texts[name]) for name in FILES)
    rows = []
    for name in NAMES:
        index, line = offsets['mm' + name]
        base_idx = offsets['mm' + name + '_BASE_IDX'][0]
        base = ip[f'GC_BASE__INST0_SEG{base_idx}'][0]
        rows.append(dict(name=name, base_idx=base_idx, base_dword=base,
                         index_dword=index, byte_offset=(base + index) * 4,
                         header_line=line))
    return dict(schema=1, scope='SOURCE_DERIVED_NOT_RUNTIME_VALIDATED',
                archive_sha256=ARCHIVE_SHA, sources_sha256=hashes,
                registers=rows, fields={n: fields[n][0] for n in FIELDS})


def validate(data):
    if data['schema'] != 1 or data['scope'] != 'SOURCE_DERIVED_NOT_RUNTIME_VALIDATED':
        raise ValueError('Unexpected schema/scope')
    if data['archive_sha256'] != ARCHIVE_SHA or set(data['sources_sha256']) != set(FILES):
        raise ValueError('Unexpected provenance')
    if [r['name'] for r in data['registers']] != list(NAMES):
        raise ValueError('Unexpected names/order')
    for row in data['registers']:
        for key in ('base_idx', 'base_dword', 'index_dword', 'byte_offset', 'header_line'):
            if type(row[key]) is not int or row[key] < 0:
                raise ValueError('Invalid numeric field')
        if row['base_idx'] not in (0, 1):
            raise ValueError('Unsupported segment')
        base = {0: 0x1260, 1: 0xA000}[row['base_idx']]
        if row['base_dword'] != base or row['byte_offset'] != (base + row['index_dword']) * 4:
            raise ValueError('Wrong units/base: ' + row['name'])
        if row['byte_offset'] > 0x80000 - 4 or row['byte_offset'] % 4:
            raise ValueError('Outside reference BAR5 span')
    if set(data['fields']) != set(FIELDS):
        raise ValueError('Unexpected fields')
    for name, value in data['fields'].items():
        if type(value) is not int or not 0 <= value <= 0xFFFFFFFF:
            raise ValueError('Invalid field value: ' + name)
        if name.endswith('__SHIFT') and value >= 32:
            raise ValueError('Invalid shift')


def render(data):
    validate(data)
    lines = ['/* Generated by catalog.py; numeric AMD source facts only.',
             ' * No hardware validation or permission to arm GPU engines.',
             ' * Archive SHA-256: ' + ARCHIVE_SHA, ' */',
             '#ifndef BC250_GC_SOURCE_MAP_H', '#define BC250_GC_SOURCE_MAP_H', '',
             '#define BC250_GC_SOURCE_MAP_VERSION 1U',
             '#define BC250_GC_SOURCE_MAP_RUNTIME_VALIDATED 0U',
             '#define BC250_GC_SOURCE_BYTE_OFFSET(base_dword, index_dword) \\',
             '    (((base_dword) + (index_dword)) * 4U)', '']
    for row in data['registers']:
        stem = 'BC250_GC_' + row['name']
        lines += [f'/* AMD mm{row["name"]}, offset header line {row["header_line"]}. */',
                  f'#define {stem}_BASE_IDX {row["base_idx"]}U',
                  f'#define {stem}_BASE_DWORD 0x{row["base_dword"]:X}U',
                  f'#define {stem}_INDEX_DWORD 0x{row["index_dword"]:X}U',
                  f'#define {stem}_BYTE_OFFSET BC250_GC_SOURCE_BYTE_OFFSET( \\',
                  f'    {stem}_BASE_DWORD, {stem}_INDEX_DWORD)', '']
    for name, value in data['fields'].items():
        lines.append(f'#define BC250_GC_{name} 0x{value:X}U')
    lines += ['', '#define BC250_GC_GFX_INDEX_BROADCAST ( \\',
              '    BC250_GC_GRBM_GFX_INDEX__SA_BROADCAST_WRITES_MASK | \\',
              '    BC250_GC_GRBM_GFX_INDEX__INSTANCE_BROADCAST_WRITES_MASK | \\',
              '    BC250_GC_GRBM_GFX_INDEX__SE_BROADCAST_WRITES_MASK)', '', '#endif', '']
    return '\n'.join(lines).encode('ascii')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--archive', type=Path)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    data = import_archive(args.archive) if args.archive else json.loads(DATA.read_bytes())
    expected = render(data)
    if args.write:
        if not args.archive:
            raise ValueError('--write requires a verified primary archive')
        HEADER.parent.mkdir(parents=True, exist_ok=True)
        DATA.write_bytes((json.dumps(data, indent=2) + '\n').encode('utf-8'))
        HEADER.write_bytes(expected)
    else:
        if json.loads(DATA.read_bytes()) != data or HEADER.read_bytes() != expected:
            raise ValueError('Generated artifacts drifted')
    print('PASS: 29 source-derived registers; runtime permission remains ZERO')


if __name__ == '__main__':
    main()
